[[pages]]
path = "frontend/dashboard.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "frontend/page2.py"
name = "Page 2"
icon = "ğŸ“š"
url_path = "my_books"

[[pages]]
path = "frontend/login.py"
name = "Login"
icon = "ğŸ”’"

[[pages]]
path = "frontend/register.py"
name = "Register"
icon = "ğŸ”‘"

[[pages]]
path = "frontend/logout.py"
name = "Logout"
icon = "ğŸšª"

[[pages]]
path = "admin/admin.py"
name = "Admin"
icon = "ğŸ”§"

[[pages]]
path = "admin/admin2.py"
name = "Admin 2"
icon = "ğŸ”§"

[[pages]]
path = "frontend/user.py"
name = "Your Profile"
icon = "ğŸ‘¤"

[client]
showSidebarNavigation = false
showTopNavigation = true